### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by kmorber** [phlbnks/mediael#2]
1. the image is disappearing whenever i start playback.
2. in IE9 the player is flickering when i move the mouse and image not shown, and the download link is displayed, even i disabled it.

http://3klang-djcrew.de/index.php?option=com_content&view=article&id=11&Itemid=12

**Comment by phlbnks** [comment]
Hi,

The main problem seems to be that the audio file you are trying to play does not exist..! 

The reason you see the image then it disappears is that the image is a "Poster Image" - these are really designed for videos, and just a placeholder to be replaced by the video once it starts playing. If you want to have an image there constantly I suggest you put that in a parent div with the audio player below it. 

If you still have problems please provide more information - which version of the plugin, which Joomla version, which OS, and what file formats you are providing.
